# Generated by Django 4.0.1 on 2022-01-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='tracker_app.task', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_tasks', to='tracker_app.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'db_table': 'tasktypes',
            },
        ),
    ]
