# Generated by Django 4.0.1 on 2022-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='tasks', through='tracker_app.TaskType', to='tracker_app.Type'),
        ),
    ]
