# Generated by Django 4.0.1 on 2022-02-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='summary',
            new_name='name',
        ),
    ]
