# Generated by Django 4.0.1 on 2022-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_task_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='types',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', through='tracker_app.TaskType', to='tracker_app.Type'),
        ),
    ]
