# Generated by Django 4.0.1 on 2022-01-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_remove_task_types_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='tracker_app.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_tasks', to='tracker_app.type', verbose_name='Тип'),
        ),
    ]
