# Generated by Django 4.0.1 on 2022-01-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_alter_tasktype_task_alter_tasktype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата создания')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проэкт',
                'verbose_name_plural': 'Проэкты',
                'db_table': 'projects',
            },
        ),
    ]
